---
- name: "Prepare for demo execution"
  hosts: localhost
#  vars:
#  - demo_hosting_api_fqdn: 
#  - demo_hosting_env: 
#  - demo_projectname: 
#  - demo_scm_url: 
#  - demo_username: 
#  - demo_token: 
  roles:
  - role: common

- name: "Write the demo json"
  hosts: localhost
  roles:
  - role: populatejson 

- name: "Load Up the API doc"
  hosts: localhost
  vars: 
  - api_server_fqdn: "labs-api.{{ demo_hosting_env }}"
  - api_server_port: "80"
  roles:
  - role: createapidoc

- name: "Run ansible-stacks"
  vars:
    openshift_user: "{{ demo_username }}"
    openshift_token: "{{ demo_token }}"
    api_document_file: "{{ demo_json_file }}"
  include: ../playbooks/load_infra_local.yml 

- name: "Get Jenkinsfile for demo and populate Jenkins"
  hosts: localhost
  roles:
  - role: jenkinsfile
  - role: createjenkinsjob
  # - role: seedjenkins

- name: "Demo prep clean-up"
  hosts: localhost
  roles:
  - role: cleanup

